# Generated by Django 5.0.6 on 2024-05-18 11:31

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='favor',
            new_name='favors',
        ),
        migrations.AddField(
            model_name='order',
            name='favor_quantities',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
