# Generated by Django 5.0.6 on 2024-05-24 19:20

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0002_rename_favor_order_favors_order_favor_quantities'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='medic.doctorcategory'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_doctors', to='medic.doctorcategory'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medic.doctorspecialization'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 29))]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 5, 29))]),
        ),
    ]
